obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0, 0.2], [-0.6, 0.2], [-0.6, -0.2], [0, -0.2]]
#robot_radius: 0.4
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: -1.0, max_obstacle_height: 0.5}